# Generated by Django 3.0.6 on 2020-11-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep02', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
